### PR TITLE
Add support for AD auth

### PR DESCRIPTION
**Pull request by nirinchev**

### CODE REVIEW

**Comment by jpsim** [comment]
If we start introducing changes that break syncing between different versions of the demo, we should document it in the README. An authentication method that is only supported by one version of the app counts as that.

**Comment by AndyDentFree** [comment]
>An authentication method that is only supported by one version of the app counts as that. (breaking change - break syncing between different versions of the demo)

Note seems to me this is only a _breaking sync_ problem **until** we have answered the issue [Connect multiple authentication methods to single SyncUser](https://github.com/realm/realm-mobile-platform/issues/29)?

Long-term, it should be completely OK to use different auth methods on different devices or at different times on the same device.

**Comment by jpsim** [comment]
> Note seems to me this is only a breaking sync problem until we have answered the issue Connect multiple authentication methods to single SyncUser?

No. With username/password, all versions of RealmTasks can interoperate and sync between each other.

With Active Directory auth (or CloudKit for that matter), if you create an account with the Xamarin version, you can't also authenticate to that same account with any other version of RealmTasks.

**Comment by nirinchev** [comment]
That's correct. The reasoning for exposing that in the Xamarin version is to have a sample that uses AD we can point interested customers at. I'll add a note in the readme about it.

**Comment by jpsim** [comment]
Thanks, that's all I wanted!

**Pull request merged**
